# Generated by Django 6.0.5 on 2026-06-01 19:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_id', models.CharField(max_length=50, unique=True)),
                ('material_name', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receipt_pdf', models.FileField(upload_to='receipts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('extracted_data', models.JSONField(blank=True, default=dict)),
                ('vendor_name', models.CharField(max_length=255)),
                ('date_received', models.DateField()),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=100, null=True)),
                ('hsn_code', models.CharField(blank=True, max_length=50, null=True)),
                ('storage_location', models.CharField(blank=True, max_length=255, null=True)),
                ('condition_notes', models.TextField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_received'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('INITIAL', 'Initial Stock from Receipt'), ('TAKE', 'Material Taken by Directorate'), ('RETURN', 'Material Returned'), ('ADJUSTMENT', 'Quantity Adjustment')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('directorate', models.CharField(max_length=255)),
                ('return_reason', models.CharField(blank=True, choices=[('DAMAGED', 'Damaged'), ('DEFECTIVE', 'Defective'), ('EXCESS', 'Excess Quantity'), ('WRONG_ITEM', 'Wrong Item Received'), ('QUALITY_ISSUE', 'Quality Issue'), ('OTHER', 'Other')], max_length=50, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('transaction_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='documents.material')),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='InventoryBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='documents.material')),
            ],
            options={
                'ordering': ['material__material_name'],
            },
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['material_id'], name='documents_m_materia_6639ce_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['-date_received'], name='documents_m_date_re_d45901_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['vendor_name'], name='documents_m_vendor__56bd4b_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['material', '-transaction_date'], name='documents_i_materia_2433a1_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['action', '-transaction_date'], name='documents_i_action_d10fd6_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['directorate'], name='documents_i_directo_6481aa_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorybalance',
            index=models.Index(fields=['material'], name='documents_i_materia_ba583f_idx'),
        ),
    ]
