# Generated by Django 6.0.5 on 2026-06-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='barcode_data',
            field=models.CharField(blank=True, help_text='Barcode data (usually same as material_id)', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='material',
            name='barcode_image',
            field=models.ImageField(blank=True, help_text='Auto-generated barcode image for this material', null=True, upload_to='barcodes/'),
        ),
    ]
