# Generated by Django 6.0.5 on 2026-06-18 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_material_barcode_data_material_barcode_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='consignee',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='pl_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='PL No.'),
        ),
        migrations.AddField(
            model_name='material',
            name='po_at_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='PO/AT No.'),
        ),
        migrations.AddField(
            model_name='material',
            name='r_note_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='R/Note No.'),
        ),
    ]
