# Generated by Django 6.0.5 on 2026-06-19 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_material_consignee_material_pl_no_material_po_at_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='batch_number',
        ),
        migrations.AddField(
            model_name='material',
            name='ro_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='RO Number'),
        ),
        migrations.AddField(
            model_name='material',
            name='vendor_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vendor Code'),
        ),
    ]
