# Generated by Django 6.0.5 on 2026-06-22 06:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_remove_material_batch_number_material_ro_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='material',
            name='documents_m_materia_6639ce_idx',
        ),
        migrations.AddField(
            model_name='material',
            name='serial_number',
            field=models.IntegerField(default=1, unique=True, verbose_name='Serial Number'),
        ),
        migrations.AlterField(
            model_name='material',
            name='barcode_data',
            field=models.CharField(blank=True, help_text='Barcode data (usually same as serial_number)', max_length=50, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['serial_number'], name='documents_m_serial__dc0c2f_idx'),
        ),
        migrations.RemoveField(
            model_name='material',
            name='material_id',
        ),
    ]
