# Generated by Django 6.0.5 on 2026-06-01 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator'), ('USER', 'Regular User')], default='USER', max_length=20)),
                ('department', models.CharField(blank=True, choices=[('HR', 'Human Resources'), ('FINANCE', 'Finance'), ('IT', 'Information Technology'), ('LEGAL', 'Legal'), ('ADMIN', 'Administration'), ('OPERATIONS', 'Operations'), ('PROCUREMENT', 'Procurement'), ('OTHER', 'Other')], max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
