# Generated by Django 6.0.5 on 2026-06-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_temp_password',
            field=models.BooleanField(default=False),
        ),
    ]
